name: spark-ui
services:
  node:
    type: node:18
    scanner: false
    ports:
      - 5173:5173
    build:
      - npm install
proxy:
  node:
    - spark-ui.local:5173
tooling:
  dev:
    service: node
    cmd: npm run dev
  build:
    service: node
    cmd: npm run build
