name: spark
services:
  api:
    type: php:8.1
    via: apache
    ssl: true
    webroot: api/web
    composer_version: 2-latest
    build_as_root:
      - apt-get update -y
      - apt-get install -y apache2
      - a2enmod headers
    build:
      - composer update -d /app/api
  cache:
    type: redis:6
    persist: false
    portforward: 56381
  client:
    type: node:18
    scanner: false
    port: 5173
    build:
      - npm --prefix /app/client install
    command: npm --prefix /app/client run build && npm --prefix /app/client run dev
proxy:
  api:
    - api.spark.loc
  client:
    - spark.loc:5173
