name: spark
services:
  site:
    type: php:8.1
    via: apache
    ssl: true
    webroot: /site/web
    composer_version: 2-latest
    build_as_root:
      - a2enmod headers
    build:
      - composer update -d site
  cache:
    type: redis:6
    persist: false
    portforward: 56381
proxy:
  site:
    - spark.loc
tooling:
  php:
    service: site
    cmd: php
  composer:
    service: site
    cmd: composer -d site
    description: "Run Composer commands"
